export const CLEAR_ALERT = "CLEAR_ALERT"

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN"
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS"

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN"
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS"
export const SETUP_USER_ERROR = "SETUP_USER_ERROR"

export const LOGOUT_USER = "LOGOUT_USER"

export const CREATE_REQUEST_BEGIN = "SEND_REQUEST_TO_SERVER"
export const CREATE_REQUEST_SUCCESS = "REQUEST_PERFORMED_SUCCESFULLY"
export const CREATE_REQUEST_ERROR = "REQUEST_ERROR_FOUND"

export const GET_PENDING_LEAVES = "GET_PENDING_LEAVES"
export const GET_LEAVES_SUCCESS = "GET_LEAVES_SUCCESS"

export const GET_ALL_SECTIONS = "GET_ALL_SECTIONS"
export const GET_SECTIONS_SUCCESS = "GET_SECTIONS_SUCCESS"

export const GET_ATTENDANCE_BEGIN = "GET_ATTENDANCE_BEGIN"
export const GET_ATTENDANCE_SUCCESS = "GET_ATTENDANCE_SUCCESS"

export const GET_TIMETABLE_BEGIN = "GET_TIMETABLE_BEGIN"
export const GET_TIMETABLE_SUCCESS = "GET_TIMETABLE_SUCCESS"

export const GET_NOTIFICATION_BEGIN = "GET_NOTIFICATION_BEGIIN"
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS"

export const GET_CLASSES_BEGIN = "GET_CLASSES_BEGIN"
export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS"

export const GET_STUDENTS_BEGIN = "GET_STUDENTS_BEGIN"
export const GET_STUDENTS_SUCCESS = "GET_STUDEN_SUCCESS"